export const productList = [
  {
    id: 1,
    title: "Awei AT7",
    subtitle: "Mayer Dua Electronics",
    group: "laden",
    discount_price: 300,
    price: 350,
    image: "/products/1.png",
    size: "xl",
    color: "red",
  },
  {
    id: 2,
    title: "Awei AT7",
    subtitle: "Mayer Dua Electronics",
    group: "laden",
    discount_price: 250,
    price: 350,
    image: "/products/2.png",
    size: "xl",
    color: "red",
  },
  {
    id: 3,
    title: "Awei AT7",
    subtitle: "Mayer Dua Electronics",
    group: "laden",
    discount_price: 160,
    price: 200,
    image: "/products/3.png",
    size: "xl",
    color: "red",
  },
  {
    id: 4,
    title: "Awei AT7",
    subtitle: "Mayer Dua Electronics",
    group: "laden",
    discount_price: 300,
    price: 550,
    image: "/products/4.png",
    size: "xl",
    color: "red",
  },
  {
    id: 5,
    title: "Awei AT7",
    subtitle: "Mayer Dua Electronics",
    group: "laden",
    discount_price: 150,
    price: 230,
    image: "/products/5.png",
    size: "xl",
    color: "red",
  },
  {
    id: 6,
    title: "Awei AT7",
    subtitle: "Mayer Dua Electronics",
    group: "laden",
    discount_price: 150,
    price: 230,
    image: "/products/5.png",
    size: "xl",
    color: "red",
  }, {
    id: 3,
    title: "Awei AT7",
    subtitle: "Mayer Dua Electronics",
    group: "laden",
    discount_price: 160,
    price: 200,
    image: "/products/3.png",
    size: "xl",
    color: "red",
  }, {
    id: 5,
    title: "Awei AT7",
    subtitle: "Mayer Dua Electronics",
    group: "laden",
    discount_price: 150,
    price: 230,
    image: "/products/5.png",
    size: "xl",
    color: "red",
  },
];
